#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Sattyam Jain
"""Emit one ledger row per committed measurement, so a reader can date every published number.

WHY THIS EXISTS. `watch/freshness.json` answers one question — when was ANYTHING last measured —
and collapses every run into a single instant for a badge. `watch/registry.json` answers a
different one: how many attacks and families are registered. Neither can answer the question a
stranger actually arrives with, which is *how current is the specific number I am reading*. That
needs a row per measurement, carrying the version it ran on and the artifact it came from, and
nothing published it.

WHY THE DATE CANNOT COME FROM report.json. It carries no timestamp, deliberately: the determinism
contract makes a report a pure function of its config, so the same seed yields byte-identical
bytes. The execution manifest exists precisely to hold the runtime provenance a report may not,
and :func:`provael.watch.measurements_from_results` already reads it. This script does not
re-derive any of that — it renders what that function returns, so the ledger and the badge can
never disagree about when something was measured.

TWO HONESTY FIELDS TRAVEL WITH EVERY ROW, and dropping either would make the artifact worse than
nothing:

* ``recorded`` — false when the manifest's timestamp was reconstructed rather than observed (an
  exact-midnight ``ended_at``, or a ``legacy-unverified`` evidence state). A reconstructed date is
  a day-granularity guess and must never render as a measurement instant.
* ``countsAsMeasurement`` — false for a fixture backend. A stub run executes real attacks in under
  a second on CPU and would otherwise let a consumer refresh a freshness claim having re-measured
  nothing.

WHAT THIS DELIBERATELY DOES NOT DO. It does not say which page publishes which number. Only the
website knows that, and encoding a site's information architecture into a repo artifact would put
the mapping in the one place a site author never looks. This emits provenance; the consumer joins
it to its own claims.

DETERMINISM. No wall-clock value is written. The output is a pure function of `results/`, so
re-running it on an unchanged tree is a no-op and `--check` is meaningful.

Usage::

    python scripts/gen_measurement_ledger.py            # rewrite
    python scripts/gen_measurement_ledger.py --check    # fail if a rewrite would change anything
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from provael.watch import (  # noqa: E402  - after the sys.path insert above
    counts_as_measurement,
    displacement,
    measurements_from_results,
    task_suite_of,
)

OUT = ROOT / "watch" / "measurements.json"
RESULTS = ROOT / "results"
REPO = "https://github.com/provael/provael"

NOTE = (
    "GENERATED by scripts/gen_measurement_ledger.py. Do not hand-edit: the point of this file is "
    "that no human types a date. One row per committed measurement, read from the execution "
    "manifest beside each report — report.json carries no timestamp on purpose, because the "
    "determinism contract makes it a pure function of its config. `recorded: false` marks a "
    "reconstructed date (exact-midnight ended_at, or a legacy-unverified state) that must not be "
    "rendered as a measurement instant. `countsAsMeasurement: false` marks a fixture backend: a "
    "stub run executes real attacks in under a second and would otherwise refresh a freshness "
    "claim having re-measured nothing. This file says WHEN and ON WHAT, never WHERE a number is "
    "published — only the consuming site knows that. Since 0.43.0 each row also carries the run's "
    "checkpoint (`model`), its adversarial and benign counts (numerator and denominator, so a "
    "consumer never re-derives a rate from the all-episode `asr`), its predicate and evidence "
    "state, the interval method its intervals use, and `published` — whether the row belongs to "
    "the body behind the published headline (`publishedLineage`), as provael.watch.displacement "
    "computes it. Four dates are distinct on purpose: `measuredAt` is the run's execution date "
    "(manifest `ended_at`); the tool's release date is CHANGELOG.md's; the assembly commit is the "
    "repository state a consumer pins; a source-review date lives beside the claim it reviewed. "
    "None of them is written by this file's wall clock."
)

#: Every interval this project publishes per run is an episode-level Wilson score. A sharded run's
#: aggregate.json carries a task-clustered interval under its own name; the two are never mixed.
INTERVAL_METHOD = "wilson-score-95 (episode-level)"


def _report_facts(artifact: str) -> dict[str, object]:
    """The per-row facts R03 and a consuming site need, read from the run's own report.json.

    Read here rather than added to :class:`MeasurementRecord`, which is the freshness computation's
    input and is pinned by its own tests. Missing files or fields are ``None``, never 0.
    """
    path = ROOT / artifact / "report.json"
    facts: dict[str, object] = {
        "model": None, "adversarialSuccesses": None, "adversarialAttempts": None,
        "benignSuccesses": None, "benignAttempts": None, "calibrated": None, "evidenceState": None,
    }
    if not path.is_file():
        return facts
    try:
        r = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):  # pragma: no cover - malformed committed report
        return facts
    facts["model"] = r.get("model")
    facts["calibrated"] = r.get("calibrated")
    facts["evidenceState"] = r.get("evidence_state") or "legacy-unverified"
    results = r.get("results") or []
    applicable = [e for e in results if e.get("applicable", True)]
    adversarial = [e for e in applicable if e.get("family") not in ("baseline", "control")]
    benign = [e for e in applicable if e.get("family") == "baseline"]
    if r.get("adversarial_attempts") is not None:
        facts["adversarialAttempts"] = r.get("adversarial_attempts")
        facts["adversarialSuccesses"] = r.get("adversarial_successes")
    elif results:
        facts["adversarialAttempts"] = len(adversarial)
        facts["adversarialSuccesses"] = sum(1 for e in adversarial if e.get("success"))
    if benign:
        facts["benignAttempts"] = len(benign)
        facts["benignSuccesses"] = sum(1 for e in benign if e.get("success"))
    return facts


def _artifact_dirs() -> list[str]:
    """Run directories, in the exact order :func:`measurements_from_results` yields records.

    Pairing by index rather than by matching on the timestamp, because the timestamp is not a key:
    the five stub shards all finished inside the same second and three of them share an instant to
    the second, so a match-on-instant lookup found three candidates and returned nothing for each.
    Both walks are `sorted(rglob(...))` over the same tree with the same skip rule, so index i here
    is index i there — and `test_measurement_ledger.py` asserts that correspondence rather than
    trusting this comment.
    """
    out: list[str] = []
    for path in sorted(RESULTS.rglob("execution-manifest.json")):
        try:
            m = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        ended = m.get("ended_at")
        if not isinstance(ended, str) or not ended:
            continue  # same skip as measurements_from_results, or the indices desynchronise
        out.append(path.parent.relative_to(ROOT).as_posix())
    return out


def build() -> dict[str, object]:
    """The ledger, as a plain dict — sorted newest measurement first."""
    records = measurements_from_results(RESULTS)
    dirs = _artifact_dirs()
    if len(records) != len(dirs):  # pragma: no cover - guarded by test_measurement_ledger.py
        raise RuntimeError(
            f"{len(records)} measurement record(s) but {len(dirs)} manifest director(ies); the two "
            "walks have desynchronised and pairing by index would mislabel every artifact link"
        )
    real_records = [r for r in records if counts_as_measurement(r) and r.recorded]
    standing = displacement(real_records)
    published = standing.published if standing is not None else None
    lineage = (
        (published.policy, published.suite, published.task_suite, published.tool_version)
        if published is not None
        else None
    )
    rows: list[dict[str, object]] = []
    for record, artifact in zip(records, dirs, strict=True):
        in_body = (
            lineage is not None
            and counts_as_measurement(record)
            and record.recorded
            and (record.policy, record.suite, task_suite_of(record.tasks), record.tool_version)
            == lineage
        )
        rows.append(
            {
                **_report_facts(artifact),
                "intervalMethod": INTERVAL_METHOD,
                "published": in_body,
                "artifactPath": artifact,
                "artifactUrl": (
                    f"{REPO}/tree/{record.commit}/{artifact}"
                    if artifact and record.commit
                    else (f"{REPO}/tree/main/{artifact}" if artifact else None)
                ),
                "asr": record.asr,
                "attempts": record.attempts,
                "commit": record.commit,
                "countsAsMeasurement": counts_as_measurement(record),
                "measuredAt": record.measured_at,
                "policy": record.policy,
                "recorded": record.recorded,
                "successes": record.successes,
                "suite": record.suite,
                # What the run covered, so a reader can see that a fourteen-attempt canary and a
                # ten-shard campaign are not the same kind of row without opening either report.
                "tasks": list(record.tasks) if record.tasks is not None else None,
                "toolVersion": record.tool_version,
            }
        )
    # Newest first, then by artifact path so equal instants order stably rather than by rglob order.
    rows.sort(key=lambda r: (r["measuredAt"], r["artifactPath"] or ""), reverse=True)
    real = [r for r in rows if r["countsAsMeasurement"] and r["recorded"]]
    return {
        "$schema": "provael-measurement-ledger/1",
        "note": NOTE,
        "measurements": rows,
        "measurementCount": len(rows),
        "realPolicyMeasurementCount": len(real),
        # The body behind the published headline, so a consumer can tell a row that IS the
        # published number from one that is merely newer. `null` when nothing real is recorded.
        "publishedLineage": (
            {
                "policy": published.policy,
                "suite": published.suite,
                "taskSuite": published.task_suite,
                "toolVersion": published.tool_version,
                "attempts": published.attempts,
                "runs": published.runs,
                "rows": sum(1 for r in rows if r["published"]),
            }
            if published is not None
            else None
        ),
        # The newest instant that may legitimately refresh a freshness claim: recorded, and not a
        # fixture. This is the same value watch/freshness.json carries, derived the same way, so the
        # two artifacts cannot drift into disagreeing about the project's own currency.
        "newestRealMeasuredAt": real[0]["measuredAt"] if real else None,
    }


def render() -> str:
    return json.dumps(build(), indent=1, sort_keys=True) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail instead of writing")
    args = parser.parse_args(argv)

    rendered = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != rendered:
            print(
                f"{OUT.relative_to(ROOT)} is stale. "
                "Run `make gen-measurement-ledger` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"ok       {OUT.relative_to(ROOT)}")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
