#!/usr/bin/env python3
"""Publish the release-drift window as an artifact, so a consumer reads the answer.

WHY THIS EXISTS, and what it does NOT exist for. `watch/freshness.json` answers one question — when
was ANYTHING last measured — and a one-episode timing probe answers it. On 8 September 2026 a $0.06
probe put that badge at "today" while the published 44/50 headline was still the ten-task suite
measured nine minors earlier. The second window that catches this is
:func:`provael.watch.published_measurement` plus :func:`provael.watch.releases_behind`, and
`provael doctor` prints it — but only to whoever runs the CLI. Nothing published it, so a consumer
wanting the same three numbers had to reimplement the rule against `watch/measurements.json`, and a
reimplementation of a staleness rule drifts in the reassuring direction by default.

IT IS NOT THE CROSS-REPO DUPLICATION FIX. That was `staleAfterReleases` in `watch/release.json`
(0.41.1) — www.provael.com read its own `STALE_AFTER_RELEASES = 2` out of `src/lib/freshness.ts`
until then, and now reads the product's. This artifact publishes the *result* of applying that
window, which nothing published before.

WHY `staleAfterReleases` APPEARS HERE TOO, when `watch/release.json` already carries it. Because
the two cannot drift: both are rendered from the same `provael.watch.STALE_AFTER_RELEASES` and both
are gated by `make check-docs`, so a change to the constant that misses one file fails the build.
That is exactly the property the cross-repo copy lacked — no shared source, and neither side able to
see the other. Repeating a constant across two *generated, gated* files in one repository is a
convenience; repeating it across two hand-maintained files in two repositories was the bug.

WHAT THIS FILE DELIBERATELY DOES NOT CARRY. No `generatedAt`, or any other wall-clock value.
`gen_release_artifact.py` and `gen_measurement_ledger.py` both refuse one for the same reason, and
`test_measurement_ledger.py` asserts it by name: a wall-clock field makes the output differ on every
run, so `--check` stops meaning "this is current" and starts meaning "this was generated in the last
instant". The `check-publish-freshness` target would then fail on a clean tree. `measuredAt` carries
the "when" a reader actually wants — the instant of the measurement being described — and it is a
fact about the run rather than about the moment this script executed.

DETERMINISM. Output is a pure function of `provael.__version__` and the committed manifests under
`results/`, so re-running on an unchanged tree is a no-op and `--check` is meaningful.

Usage::

    python scripts/gen_publish_freshness_artifact.py            # rewrite
    python scripts/gen_publish_freshness_artifact.py --check    # fail if a rewrite would differ
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from provael import __version__  # noqa: E402  - after the sys.path insert above
from provael.watch import (  # noqa: E402
    STALE_AFTER_RELEASES,
    published_measurement,
    releases_behind,
)

OUT = ROOT / "watch" / "publish-freshness.json"

NOTE = (
    "GENERATED by scripts/gen_publish_freshness_artifact.py. Do not hand-edit. The PUBLISHED "
    "measurement's drift against the current release — a different question from "
    "watch/freshness.json, which reports when anything was last measured and is satisfied by a "
    "one-episode probe. `measuredWith` is the version behind the LARGEST real campaign rather than "
    "the newest record, so a probe cannot displace a 350-episode run; see "
    "provael.watch.published_measurement. `isStale` is releasesBehind > staleAfterReleases, "
    "precomputed so a consumer rendering a banner does not reimplement the comparison. "
    "`staleAfterReleases` also appears in watch/release.json: the two cannot drift, because both "
    "render from provael.watch.STALE_AFTER_RELEASES and both are gated by `make check-docs`. There "
    "is deliberately NO generatedAt — a wall-clock field would make --check fail on a clean tree, "
    "which is the same reason watch/release.json and watch/measurements.json carry none."
)


def build() -> dict[str, object]:
    """The artifact, as a plain dict. Every value derives from the ledger or the package version."""
    record = published_measurement()
    if record is None:
        # Nothing real is committed. Say so rather than emitting a zero gap: zero is the reassuring
        # answer, and a consumer cannot tell it from "measured and current".
        return {
            "$schema": "provael-publish-freshness/1",
            "note": NOTE,
            "measuredWith": None,
            "measuredAt": None,
            "releasesBehind": None,
            "staleAfterReleases": STALE_AFTER_RELEASES,
            "isStale": None,
            "currentVersion": __version__,
        }
    gap = releases_behind(record.tool_version, __version__)
    return {
        "$schema": "provael-publish-freshness/1",
        "note": NOTE,
        "measuredWith": record.tool_version,
        "measuredAt": record.measured_at,
        "releasesBehind": gap,
        "staleAfterReleases": STALE_AFTER_RELEASES,
        "isStale": None if gap is None else gap > STALE_AFTER_RELEASES,
        "currentVersion": __version__,
    }


def render() -> str:
    return json.dumps(build(), indent=1, sort_keys=True) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Publish watch/publish-freshness.json.")
    parser.add_argument("--check", action="store_true", help="fail instead of writing")
    args = parser.parse_args(argv)

    rendered = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != rendered:
            print(
                f"{OUT.relative_to(ROOT)} disagrees with provael.__version__ ({__version__}) or "
                "with the committed measurements. Run `make gen-publish-freshness` and commit the "
                "result.",
                file=sys.stderr,
            )
            return 1
        print(f"ok       {OUT.relative_to(ROOT)} ({__version__})")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({__version__})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
