#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Sattyam Jain
"""Publish the re-measurement's progress, so a page can render a denominator instead of STALE.

WHY THIS EXISTS. `watch/publish-freshness.json` says the published measurement is nine releases
old and `watch/freshness.json` says something was measured today, and between them a reader could
not learn the one thing that would change their reading of both: that a like-for-like campaign is
being measured on a current release, how much of it is banked, and when it completes. The pages
that sell the Checkpoint Report and the assessment rendered a flat STALE banner off the first file,
which was true and unhelpful in equal measure.

WHAT IT CARRIES. The plan's shape and size (from `studies/scheduled_campaign/plan.json`), the
version the campaign is pinned at (read from the lane's own `PROVAEL_PIN`, by AST, so this file
cannot disagree with the lane), the attempts it has to exceed (the published body, from
`provael.watch.displacement`), what is banked so far (from the committed shards), the committed
cadence (the workflow's own cron), and the completion that cadence projects.

NO WALL-CLOCK FIELD, like every artifact in watch/. `projectedCompletion` is dated from the newest
shard's `ended_at` plus the runs still needed — a fact about the run, not about when this script
ran — and it is null until the first shard lands, because before that the only anchor would be the
clock and `--check` would fail on every clean tree.

Usage::

    python scripts/gen_campaign_progress.py            # rewrite
    python scripts/gen_campaign_progress.py --check    # fail if a rewrite would change anything
"""

from __future__ import annotations

import argparse
import ast
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from provael.campaign import load_plan, progress  # noqa: E402
from provael.watch import displacement  # noqa: E402

OUT = ROOT / "watch" / "campaign.json"
LANE = ROOT / "examples" / "gpu-ci" / "modal_provael_gpu.py"
WORKFLOW = ROOT / ".github" / "workflows" / "gpu-scheduled.yml"

NOTE = (
    "GENERATED by scripts/gen_campaign_progress.py. Do not hand-edit. The state of the "
    "re-measurement the scheduled GPU lane is building: the declared plan "
    "(studies/scheduled_campaign/plan.json), the release it is pinned at, the attempts it has to "
    "exceed to displace the published measurement (see watch/publish-freshness.json and "
    "provael.watch.displacement), what is banked so far from the committed shards, the committed "
    "cadence, and the completion that cadence projects. `banked.attempts` counts the campaign's "
    "own shards; the body the displacement rule sums may be larger if other runs landed at the "
    "same version. There is deliberately NO generatedAt: `projected.completion` is dated from the "
    "newest shard's ended_at plus the runs still needed, and is null until the first shard lands."
)


def lane_pin(path: Path = LANE) -> str:
    """The lane's `PROVAEL_PIN`, read by AST: the lane imports modal at module scope."""
    for node in ast.parse(path.read_text(encoding="utf-8")).body:
        if (
            isinstance(node, ast.Assign)
            and any(isinstance(t, ast.Name) and t.id == "PROVAEL_PIN" for t in node.targets)
            and isinstance(node.value, ast.Constant)
            and isinstance(node.value.value, str)
        ):
            return node.value.value
    raise SystemExit(f"{path} declares no string PROVAEL_PIN")


def lane_cron(path: Path = WORKFLOW) -> str | None:
    """The workflow's schedule, read from the workflow so the cadence here is the cadence run.

    ``None`` when the workflow declares no ``schedule`` at all: the lane is paused (dispatch-only),
    and the artifact records the pause instead of a cadence nobody runs. Two schedules is still an
    error — a cadence this file cannot express is not a cadence it should project from.
    """
    workflow = yaml.safe_load(path.read_text(encoding="utf-8"))
    triggers = workflow.get(True) or workflow.get("on") or {}
    crons = [entry["cron"] for entry in triggers.get("schedule", []) if "cron" in entry]
    if not crons:
        return None
    if len(crons) != 1:
        raise SystemExit(f"{path} declares {len(crons)} cron schedules; expected at most one")
    return str(crons[0])


def build() -> dict[str, object]:
    plan = load_plan()
    standing = displacement()
    state = progress(
        plan,
        lane_pin(),
        cron=lane_cron(),
        attempts_to_displace=None if standing is None else standing.published.attempts,
        published_with=None if standing is None else standing.published.tool_version,
    )
    return {"$schema": "provael-campaign-progress/1", "note": NOTE, **state}


def render() -> str:
    return json.dumps(build(), indent=1, sort_keys=True) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Publish watch/campaign.json.")
    parser.add_argument("--check", action="store_true", help="fail instead of writing")
    args = parser.parse_args(argv)

    rendered = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != rendered:
            print(
                f"{OUT.relative_to(ROOT)} disagrees with the plan, the lane's pin, the committed "
                "shards or the workflow's cron. Run `make gen-campaign` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"ok       {OUT.relative_to(ROOT)}")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
